// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxexocgchvbmtjwenzum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZXhvY2djaHZibXRqd2VuenVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxOTcwMjcsImV4cCI6MjA1NTc3MzAyN30.nC0yqvvRdUvaImX5-ARgJoJZ906GgPYiOm0iXCO0V7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);